spring:
  datasource:
      url: jdbc:mysql://docker-mysql:3306/learningplatform?useSSL=false
      username: bartek
      password: bartek
      initialization-mode: always
      platform: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      data: classpath:data-mysql.sql
  jpa:
      hibernate.ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL8Dialect
      show-sql: true
  mail:
    host: smtp.mailtrap.io
    port: 25
    username: ebd9118ff80498
    password: 8564227e949800
    protocol: smtp
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/changelog-master.xml

server:
  error.include-message: always
  port: 8090

springdoc.swagger-ui:
  url-pattern:
      /v2/api-docs,
      /configuration/ui,
      /swagger-resources/**,
      /configuration/security,
      /swagger-ui.html,
      /webjars/**

jwt.expiration.time: 900000