spring:
  datasource:
    driver-class-name: org.postgresql.Driver;
    url:
    username:
    password:
    initialization-mode: create
    data:
      classpath:data-course-categories.sql,
      classpath:data-courses.sql,
      classpath:data-users.sql,
      classpath:data-lessons.sql,
      classpath:data-tasks.sql,
      classpath:data-enrolled-courses.sql
  jpa:
    hibernate.ddl-auto: create
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.mailtrap.io
    port: 25
    username: ebd9118ff80498
    password: 8564227e949800
    protocol: smtp